export { ContentHeader } from './ContentHeader'
export { TranslateArea } from './TranslateArea'
export { ClassTestArea } from './ClassTestArea'
export { ClassQuestionList } from './ClassQuestionList'
export { ContentPageSideArea } from './ContentPageSideArea'
