export { PageHeader } from './PageHeader'
export { TopPageCatchCopy } from './TopPageCatchCopy'
export { TranslateArea } from './TranslateArea'
export { ClassTestArea } from './ClassTestArea'
export { ClassQuestionList } from './ClassQuestionList'
export { ContentPageSideArea } from './ContentPageSideArea'
export { PointArea } from './PointArea'