export { ContentTemplate } from './contentTemplate'
export { TranslatePage } from './TranslatePage'
export { QuestionListPageTemplate } from './QuestionListPageTemplate'
export { TestPageTemplate } from './TestPageTemplate'
export { TopPageTemplate } from './TopPageTemplate'
